trigger: none

pr:
  autoCancel: true
  branches:
   include:
   - master
  paths:
   exclude:
   - README.adoc
   - Vagrantfile

variables:
- group: vault-packer-build

jobs:
- job: build_vault
  pool:
    vmImage: 'Ubuntu-18.04'
  steps:
  - task: riezebosch.Packer.PackerTool.PackerTool@0
    displayName: 'Use Packer'
    inputs:
      version: $(PACKER_VERSION)

  - bash: |
          sudo apt update -y
          sudo apt install -y ruby ruby-dev libffi-dev build-essential
          sudo gem install inspec-bin ed25519 bcrypt_pbkdf --no-rdoc --no-ri inspec-bin

  - bash: |
          sudo apt install jq -y

  - bash: |
          cd $(system.defaultWorkingDirectory)
          pwd
          ls -la
          inspec check $(system.defaultWorkingDirectory)/../tests/local/common --chef-license=accept-silent

  - bash: |
          packer validate --syntax-only $(system.defaultWorkingDirectory)/../build.json

  - bash: |
          cd $(system.defaultWorkingDirectory)
          packer build \
          -only=azure \
          --var-file=../variables-pipeline.json \
          -var "git_ref=$(git rev-parse --abbrev-ref HEAD)" \
          -var "git_commit_sha=PRTEST-$(git rev-parse --short HEAD)" \
          -var "client_id=$(ARM_CLIENT_ID)" \
          -var "client_secret=$(ARM_CLIENT_SECRET)" \
          -var "build_resource_group_name=$(ARM_RESOURCE_GROUP)" \
          -var "managed_image_resource_group_name=$(ARM_RESOURCE_GROUP)" \
          ../build.json

  - bash: |
          az login --service-principal \
          -u $(ARM_CLIENT_ID) \
          -p $(ARM_CLIENT_SECRET) \
          -t 513294a0-3e20-41b2-a970-6d30bf1546fa

  - bash: |
          export SIG_VERSION=`cat ../variables-pipeline.json | jq -r '.sig_version'`
          echo $SIG_VERSION
          az sig image-version delete \
          --subscription $(ARM_SUBSCRIPTION_ID) \
          --resource-group $(ARM_RESOURCE_GROUP) \
          --gallery-name infra_testing_demo \
          --gallery-image-definition vault \
          --gallery-image-version $SIG_VERSION --debug
          az image delete \
          --subscription $(ARM_SUBSCRIPTION_ID) \
          --resource-group $(ARM_RESOURCE_GROUP) \
          -n vault-PRTEST-$(git rev-parse --short HEAD)
